[experiment]
name = "bert_classifier"

[data]
train_csv = "./data/train.csv"
val_csv = "./data/val.csv"
text_field = "review"
label_field = "label"
encoding = "transformer"
max_length = 256
pretrained_model_name = "hfl/chinese-roberta-wwm-ext"

[model]
name = "bert_classifier"

[model_parameters]
pretrained_model_name = "hfl/chinese-roberta-wwm-ext"
num_classes = 2
classifier_hidden_dim = 512
dropout = 0.08
freeze_encoder = true
pooling_strategy = "cls"

[training]
batch_size = 12
learning_rate = 5.1261745611921186e-05
encoder_learning_rate = 3.9139370975328926e-05
weight_decay = 0.0016864974751216414
epochs = 4
val_steps = 417
seed = 42
warmup_ratio = 0.1499362438641551
final_lr_scale = 0.05

[output]
checkpoint_dir = "./checkpoints/bert_classifier"
log_dir = "./runs/bert_classifier"
